Fix "TypeError: __init__() missing 1 required positional argument: 'name'"
Happened during ```agp --vienna```:
Checking Niederösterreich (3) for Diesel prices...