Fix "TypeError: __init__() missing 1 required positional argument: 'address'"
For some gas stations not all information is available. For example, the gas station "AVIA mit Bedienung" has only a place name, but no address.